env:
  browser: true
  es6: true
  node: true
extends:
  - 'plugin:react/recommended'
  - google
  - prettier # 上の定義の整形に関するルールを無効化
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - prettier # eslint-plugin-prettier の追加
rules:
  # 関数の複雑さを 10 以下にする
  complexity: ['error', 10]
  # React のプロパティの型チェックを省略する (TypeScript でチェックされるため)
  react/prop-types: off
  # prettier のチェックでErrorとするための設定。
  prettier/prettier:
    - error
  # TypeScriptで誤検知されるLintルールを上書き
  'no-unused-vars': off
  '@typescript-eslint/no-unused-vars': error